name: Test

on:
  push

jobs:
  deploy:
    name: Test the Review Apps Database Deployment Action (deploy)
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - id: deploy-database
        name: Deploy Database
        uses: blissdotdev/action-review-apps-database@main
        with:
          command: deploy
          database-host: localhost
          database-user: postgres
          database-password: postgres
          prefix: review-apps-test
          event-number: 25
